name: Feature request
description: Suggest a new feature or improvement
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve
      description: What's the current pain point or limitation motivating this request?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: How do you imagine this would work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
